# Generated by Django 4.2.30 on 2026-08-11 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membresias', '0001_initial'),
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresiasocio',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='socios.socio'),
        ),
    ]
